parameters:
#    tim_user.example.class: Tim\UserBundle\Example

services:
#    tim_user.example:
#        class: %tim_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
