parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: '3306'
    database_name: symfony
    database_user: tim
    database_password: tim
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: 8872c2f76e54105e76f8c2cbaa56fcac7
    database_path: null
