security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext

  role_hierarchy:
    ROLE_ADMIN:       ROLE_JOUEUR
    ROLE_SUPER_ADMIN: [ROLE_JOUEUR, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    in_memory:
      memory:
        users:
          user:  { password: p, roles: [ 'ROLE_JOUEUR' ] }
          admin: { password: p, roles: [ 'ROLE_ADMIN' ] }

  firewalls:
    dev:
      pattern:  ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern:   ^/
      anonymous: true
      provider:  in_memory
      form_login:
        login_path: tim_user_login
        check_path: login_check
        default_target_path: /home
      logout:
        path:   logout
        target: /home
        invalidate_session: false

  access_control:
    - { path: ^/game, roles: ROLE_JOUEUR }
