tim_tron_homepage:
  pattern:  /home/
  defaults: { _controller: TimTronBundle:Home:index }
  requirements:
    _method:  GET

tim_tron_about:
  pattern:  /home/about/
  defaults: { _controller: TimTronBundle:Home:about }
  requirements:
    _method:  GET

tim_tron_contact:
  pattern:  /home/contact/
  defaults: { _controller: TimTronBundle:Home:contact }
  requirements:
    _method:  GET

tim_tron_rules:
  pattern:  /home/rules/
  defaults: { _controller: TimTronBundle:Home:rules }
  requirements:
    _method:  GET

tim_tron_game:
  pattern:  /game/
  defaults: { _controller: TimTronBundle:Game:index }
  requirements:
    _method:  GET

tim_tron_game_create:
  pattern:  /game/new
  defaults: { _controller: TimTronBundle:Game:create }
  requirements:
    _method:  POST

tim_tron_game_run:
  pattern:  /game/run/{id}
  defaults: { _controller: TimTronBundle:Game:run }
  requirements:
    _method:  GET

tim_tron_game_join:
  pattern:  /game/join/{id}
  defaults: { _controller: TimTronBundle:Game:join }
  requirements:
    _method:  POST
