parameters:
#    tim_tron.example.class: Tim\TronBundle\Example

services:
#    tim_tron.example:
#        class: %tim_tron.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
